### ISSUE TITLE
deprecated feature

### ISSUE THREAD

**Issue by n3bojs4** [chef-cookbooks/push-jobs#96]
### Cookbook version

3.2.0
### Chef-client version

12.11.18
### Platform Details

RHEL 7
### Scenario:

Everything is ok, it's just a deprecated code
### Expected Result:

No more warnings :)
### Actual Result:

Deprecated features used!

An attempt was made to change version from :latest to nil by calling version(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location:
- /var/chef/cache/cookbooks/**push-jobs/recipes/package.rb:45:in `block in from_file'**

**Comment by marchenkov** [comment]
Ubuntu 14.04 - same deprecated warning.
Chef version same - 12.11.18

Deprecated features used!
  An attempt was made to change version from :latest to nil by calling version(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location:
    - /var/chef/cache/cookbooks/push-jobs/recipes/package.rb:52:in `block in from_file'

How fix?

**Comment by iennae** [comment]
Thanks for reporting. We are working to refactor this code. This happens when the version isn't explicitly set.

**Comment by iennae** [comment]
This is fixed in 5.0.0 of the cookbook. Thanks again for reporting.
